config:
  connector:
    type: "proxmox"
    url: "proxmox.example.com"
    user: "root@pam"
    password: "password"
  machines:
    - name: "machine1"
      ip: "10.10.10.10"
    - name: "machine2"
      ip: "10.10.10.11"