config:
  connector:
    connector_type: "proxmox"
    connector_url: "https://proxmox.example.com:8006/api2/json"
    connector_user: "root@pam"
    connector_password: "password"
  machines:
    - machine_name: "machine1"
      machine_ip: "10.10.10.10"
    - machine_name: "machine2"
      machine_ip: "10.10.10.11"